# Generated by Django 5.2.5 on 2025-08-22 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("manager", "Менеджер"),
                            ("user", "Пользователь"),
                            ("guest", "Гость"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Название роли",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание роли"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Роль по умолчанию"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Роль",
                "verbose_name_plural": "Роли",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResourcePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_name",
                    models.CharField(
                        choices=[
                            ("users", "Пользователи"),
                            ("products", "Товары"),
                            ("orders", "Заказы"),
                            ("permissions", "Разрешения"),
                        ],
                        max_length=50,
                        verbose_name="Название ресурса",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("module", "Модуль"), ("object", "Объект")],
                        default="module",
                        max_length=20,
                        verbose_name="Тип ресурса",
                    ),
                ),
                (
                    "read_permission",
                    models.BooleanField(default=False, verbose_name="Чтение своих"),
                ),
                (
                    "read_all_permission",
                    models.BooleanField(default=False, verbose_name="Чтение всех"),
                ),
                (
                    "create_permission",
                    models.BooleanField(default=False, verbose_name="Создание"),
                ),
                (
                    "update_permission",
                    models.BooleanField(default=False, verbose_name="Обновление своих"),
                ),
                (
                    "update_all_permission",
                    models.BooleanField(default=False, verbose_name="Обновление всех"),
                ),
                (
                    "delete_permission",
                    models.BooleanField(default=False, verbose_name="Удаление своих"),
                ),
                (
                    "delete_all_permission",
                    models.BooleanField(default=False, verbose_name="Удаление всех"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_permissions",
                        to="permissions.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разрешение на ресурс",
                "verbose_name_plural": "Разрешения на ресурсы",
                "ordering": ["role__name", "resource_name"],
                "unique_together": {("role", "resource_name", "resource_type")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата назначения"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначил",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="permissions.role",
                        verbose_name="Роль",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль пользователя",
                "verbose_name_plural": "Роли пользователей",
                "ordering": ["-assigned_at"],
                "unique_together": {("user", "role")},
            },
        ),
    ]
