# Generated by Django 5.2.5 on 2025-08-22 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.role",
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название ресурса"),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("product", "Продукт"),
                            ("order", "Заказ"),
                            ("user", "Пользователь"),
                        ],
                        max_length=20,
                        verbose_name="Тип ресурса",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресурс",
                "verbose_name_plural": "Ресурсы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("product", "Продукт"),
                            ("order", "Заказ"),
                            ("user", "Пользователь"),
                        ],
                        max_length=20,
                        verbose_name="Тип ресурса",
                    ),
                ),
                (
                    "can_create",
                    models.BooleanField(default=False, verbose_name="Может создавать"),
                ),
                (
                    "can_read",
                    models.BooleanField(default=False, verbose_name="Может читать"),
                ),
                (
                    "can_update",
                    models.BooleanField(default=False, verbose_name="Может обновлять"),
                ),
                (
                    "can_delete",
                    models.BooleanField(default=False, verbose_name="Может удалять"),
                ),
                (
                    "can_manage_others",
                    models.BooleanField(
                        default=False, verbose_name="Может управлять чужими"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
            options={
                "verbose_name": "Разрешение роли",
                "verbose_name_plural": "Разрешения ролей",
                "ordering": ["role__name", "resource_type"],
                "unique_together": {("role", "resource_type")},
            },
        ),
        migrations.DeleteModel(
            name="ResourcePermission",
        ),
    ]
