# Generated by Django 5.2.5 on 2025-08-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0002_remove_role_updated_at_alter_userrole_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Название роли"
            ),
        ),
    ]
