# Generated by Django 5.2.5 on 2025-08-23 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0003_alter_role_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resource",
        ),
    ]
