# Generated by Django 5.2.5 on 2025-08-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0004_delete_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название ресурса"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание ресурса"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип ресурса",
                "verbose_name_plural": "Типы ресурсов",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="rolepermission",
            options={
                "ordering": ["role__name", "resource_type__name"],
                "verbose_name": "Разрешение роли",
                "verbose_name_plural": "Разрешения ролей",
            },
        ),
        migrations.AlterField(
            model_name="rolepermission",
            name="resource_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="permissions.resourcetype",
                verbose_name="Тип ресурса",
            ),
        ),
    ]
